name: build_and_push

on:
  push:
    branches:
      - "main"

env:
  ALPINE_VERSION: 3.17
  NGINX_VERSION: 1.22.1

jobs:
  build&push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx_fancy_index:${{ env.NGINX_VERSION }} 
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            NGINX_VERSION=${{ env.NGINX_VERSION }}